import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { meta } from "@/components/page-kit";
import logo from "@/assets/arcova-logo.png.asset.json";
export const Route=createFileRoute("/auth")({head:()=>meta("Sign in","Secure access to ARCOVA conversations, policies, watchlists and reports."),component:Auth});
function Auth(){const nav=useNavigate();const [mode,setMode]=useState<"signin"|"signup"|"forgot">("signin");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{if(mode==="forgot"){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(error)throw error;setMessage("Check your email for a secure reset link.");}else if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(error)throw error;setMessage(data.session?"Account created.":"Check your email to confirm your account.");if(data.session)await nav({to:"/agent"});}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await nav({to:"/agent"});}}catch(e){setMessage(e instanceof Error?e.message:"Authentication unavailable.")}finally{setBusy(false)}}
return <section className="auth-page"><form className="auth-panel" onSubmit={submit}><img src={logo.url} alt="ARCOVA"/><span className="eyebrow">SECURE ACCESS</span><h1>{mode==="signup"?"Create account":mode==="forgot"?"Reset access":"Welcome back"}</h1><p>Account-synced agent conversations, policies and audit history.</p><label>EMAIL<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label>{mode!=="forgot"&&<label>PASSWORD<Input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete={mode==="signup"?"new-password":"current-password"}/></label>}<Button type="submit" disabled={busy}>{busy?"PROCESSING…":mode==="signup"?"CREATE ACCOUNT":mode==="forgot"?"SEND RESET LINK":"SIGN IN"}</Button><Button type="button" variant="outline" onClick={()=>lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin+"/auth"})}>CONTINUE WITH GOOGLE</Button>{message&&<p className="form-message">{message}</p>}<div className="auth-switch"><button type="button" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"CREATE AN ACCOUNT":"SIGN IN INSTEAD"}</button><button type="button" onClick={()=>setMode("forgot")}>FORGOT PASSWORD</button></div></form></section>}
