import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Bot, Braces, Check, ChevronRight, CircleDot, LockKeyhole, Network, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { processSteps } from "@/lib/arcova";
import banner from "@/assets/arcova-banner.png.asset.json";
import background from "@/assets/background.png.asset.json";
import logo from "@/assets/arcova-logo.png.asset.json";
import { DataPanel, Metric, meta } from "@/components/page-kit";
export const Route=createFileRoute("/")({head:()=>meta("Autonomous Intelligence for Tokenized Markets","ARCOVA is an autonomous financial intelligence agent for researching, modeling and monitoring tokenized markets on Arc."),component:Home});
const scenarios=[{name:"BULL CASE",tone:"positive",copy:"Favorable regime, catalyst follow-through and improving liquidity."},{name:"BASE CASE",tone:"neutral",copy:"Current conditions persist within the model's central assumptions."},{name:"BEAR CASE",tone:"negative",copy:"Adverse regime, weakened liquidity or thesis invalidation."}];
function Home(){return <>
<section className="hero" style={{backgroundImage:`linear-gradient(to bottom, oklch(0.08 0.01 260 / .25), var(--background)), url(${background.url})`}}><div className="hero-noise"/><div className="hero-content"><div><span className="eyebrow"><CircleDot/> ARC-NATIVE AUTONOMOUS AGENT</span><h1>Autonomous Intelligence<br/>for <em>Tokenized Markets.</em></h1><p>ARCOVA researches tokenized assets, models scenarios, controls risk and executes only what you authorize — with every decision preserved in an auditable history.</p><div className="hero-actions"><Button size="lg" asChild><Link to="/agent">LAUNCH AGENT <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><Link to="/terminal">OPEN TERMINAL <Braces/></Link></Button></div><div className="trust-line"><span><Check/> Scenario-based</span><span><Check/> Policy-controlled</span><span><Check/> Auditable</span></div></div><img className="hero-banner" src={banner.url} alt="ARCOVA autonomous financial intelligence"/></div></section>
<section className="market-strip"><span className="status unavailable">○ DATA UNAVAILABLE</span><span>MARKET FEED</span><span>ARC MAINNET</span><span>SETTLEMENT · USDC</span><a href="https://argus.world" target="_blank" rel="noreferrer">ARGUS ↗</a></section>
<section className="section-wrap intro-grid"><div><span className="eyebrow">THE INTELLIGENCE LAYER</span><h2>One agent. The complete decision lifecycle.</h2></div><div><p className="lead">ARCOVA turns fragmented market information into transparent, scenario-based decisions across research, portfolio construction and permitted execution.</p><Button variant="link" asChild><Link to="/about">HOW ARCOVA WORKS <ArrowRight/></Link></Button></div></section>
<section className="section-wrap"><div className="process-grid">{processSteps.map(([n,d,I],i)=><article className="process-step" key={n}><span>0{i+1}</span><I/><h3>{n}</h3><p>{d}</p></article>)}</div></section>
<section className="dark-band"><div className="section-wrap split"><div><span className="eyebrow">LIVE INTELLIGENCE</span><h2>Signal, with its provenance intact.</h2><p>Every market observation must retain its source, timestamp and status. ARCOVA will not manufacture a story when a feed is missing.</p><Button asChild><Link to="/intelligence">OPEN INTELLIGENCE <ArrowRight/></Link></Button></div><DataPanel title="MARKET REGIME"><div className="data-grid"><Metric label="REGIME"/><Metric label="LIQUIDITY"/><Metric label="VOLATILITY"/><Metric label="SENTIMENT"/></div></DataPanel></div></section>
<section className="section-wrap"><div className="section-heading"><div><span className="eyebrow">TOKENIZED ASSET DISCOVERY</span><h2>A clearer view of the market.</h2></div><Button variant="outline" asChild><Link to="/markets">EXPLORE MARKETS <ArrowRight/></Link></Button></div><div className="table-shell"><div className="table-head"><span>ASSET</span><span>PRICE</span><span>24H</span><span>LIQUIDITY</span><span>MODEL VIEW</span></div><div className="inline-empty">CONNECTING TO DATA PROVIDER</div></div></section>
<section className="section-wrap scenario-section"><div><span className="eyebrow">SCENARIO ENGINE</span><h2>Forecasts are possibilities,<br/>not promises.</h2><p className="lead">Each model view exposes confidence, assumptions, catalysts and invalidation risks across distinct market regimes.</p></div><div className="scenario-grid">{scenarios.map(s=><article className={`scenario ${s.tone}`} key={s.name}><span>{s.name}</span><h3>DATA UNAVAILABLE</h3><p>{s.copy}</p><div className="scenario-meter"><i/></div></article>)}</div></section>
<section className="dark-band"><div className="section-wrap decision-layout"><div className="decision-card"><div className="panel-head"><span>MODEL DECISION · EXAMPLE FORMAT</span><span className="status unavailable">NOT LIVE</span></div><img src={logo.url} alt="ARCOVA agent"/><div><small>ANALYTICAL OUTPUT</small><h3>MODEL VIEW · WATCH</h3><p>This illustrative frame demonstrates ARCOVA's decision structure. It is not an asset recommendation and contains no fabricated market values.</p></div><div className="decision-meta"><Metric label="CONFIDENCE"/><Metric label="HORIZON"/><Metric label="RISK"/></div></div><div><span className="eyebrow">EXPLAINABLE BY DESIGN</span><h2>Every decision carries its reasoning.</h2><ul className="check-list"><li><Check/> Data sources and freshness</li><li><Check/> Model assumptions</li><li><Check/> Scenario probabilities</li><li><Check/> Key catalysts and risks</li><li><Check/> Thesis invalidation conditions</li></ul></div></div></section>
<section className="section-wrap split"><div><span className="eyebrow">PORTFOLIO INTELLIGENCE</span><h2>Strategy within constraints.</h2><p>Set capital, risk profile, time horizon, position limits, allowed assets and rebalancing policy. ARCOVA proposes an allocation with reasons and risk — never an unbounded mandate.</p><Button asChild><Link to="/portfolio">VIEW PORTFOLIO <ArrowRight/></Link></Button></div><div className="allocation"><div className="alloc-ring"><span>NO WALLET<br/>CONNECTED</span></div><div className="policy-list"><span><i/>MAX POSITION</span><span><i/>DAILY EXPOSURE</span><span><i/>ASSET WHITELIST</span><span><i/>REBALANCING</span></div></div></section>
<section className="section-wrap"><div className="section-heading"><div><span className="eyebrow">RISK & PERMISSION LAYER</span><h2>Autonomy with hard boundaries.</h2></div><ShieldCheck className="section-icon"/></div><div className="policy-flow">{["USER POLICY","AGENT DECISION","RISK CHECK","PERMISSION CHECK","USER APPROVAL","TRANSACTION","ONCHAIN CONFIRMATION"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}{i<6&&<ChevronRight/>}</div>)}</div><p className="callout"><LockKeyhole/> ARCOVA never auto-submits a transaction without the authorization required by your configured policy.</p></section>
<section className="dark-band"><div className="section-wrap split"><div><span className="eyebrow">AUDIT TRAIL</span><h2>Decision history that stands up to scrutiny.</h2><p>Inputs, assumptions, model view, confidence, risk checks, approval state and onchain confirmation are connected in one timestamped record.</p><Button variant="outline" asChild><Link to="/activity">VIEW ACTIVITY <ArrowRight/></Link></Button></div><DataPanel title="LATEST DECISIONS"/></div></section>
<section className="section-wrap infra"><div><Network/><span className="eyebrow">ARC INFRASTRUCTURE</span><h2>Research. Decide. Execute. On Arc.</h2><p>ARCOVA is designed around Arc Mainnet and USDC settlement. Connection details, contracts and explorer links remain unavailable until officially configured.</p></div><div className="data-grid"><Metric label="NETWORK" value="ARC MAINNET"/><Metric label="SETTLEMENT" value="USDC"/><Metric label="RPC STATUS"/><Metric label="CONTRACT" value="COMING SOON"/></div></section>
<section className="section-wrap"><span className="eyebrow">ROADMAP</span><h2>Building in public, without invented dates.</h2><div className="roadmap-row">{[["BUILDING","Agent research & audit foundation"],["UPCOMING","Verified market data integrations"],["EXPLORING","Policy-controlled onchain execution"]].map(([s,t])=><article key={s}><span className="status">{s}</span><h3>{t}</h3></article>)}</div></section>
<section className="section-wrap faq"><span className="eyebrow">FAQ</span><h2>Questions, answered directly.</h2>{[["Does ARCOVA guarantee returns?","No. ARCOVA provides scenario-based analysis and model views. Markets are uncertain, and all models can be wrong."],["Can the agent trade without permission?","No. Every transaction passes through user policy, risk and permission checks. Required approval cannot be bypassed."],["Where does market data come from?","Only configured, validated external providers. If no provider is connected, ARCOVA shows data unavailable."],["Is $ARCV live?","The contract and token metrics are coming soon. ARCOVA will never display an unverified address or invented supply data."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
<section className="final-cta" style={{backgroundImage:`linear-gradient(var(--overlay),var(--overlay)),url(${banner.url})`}}><span className="eyebrow">ARCOVA</span><h2>Research. Decide. Execute.<br/>On Arc.</h2><div><Button size="lg" asChild><Link to="/agent"><Bot/>LAUNCH AGENT</Link></Button><Button size="lg" variant="outline" asChild><Link to="/docs">READ THE DOCS</Link></Button></div></section>
</>}
